### ISSUE TITLE
Remove Babel

### ISSUE THREAD

**Issue by gr0uch** [fortunejs/fortune-json-api#10]
Babel considered harmful.

**Comment by capelio** [comment]
Just a question of curiosity as a user of babel in other projects: why is it considered harmful for the JSON API module?

**Comment by gr0uch** [comment]
It's completely unnecessary, particularly on Node.js 4+ which already has good ES6 support. And also in my opinion bad for the ecosystem, makes everything more complicated than it needs to be.

**Comment by capelio** [comment]
Ah, gotcha. Makes sense. Will Node.js v4.x become the minimum for Fortune.js moving forward?

**Comment by gr0uch** [comment]
For Node.js-specific modules like this one, yes.

Fortune.js will continue to be an ES5 project for the forseeable future, for performance and compatibility reasons (except where ES6 performance is better, i.e. Map, Set, etc.)

**Comment by gr0uch** [comment]
Done.
