### ISSUE TITLE
Is `filter` implemented?

### ISSUE THREAD

**Issue by yankeeinlondon** [fortunejs/fortune-json-api#15]
the JSON-API is a bit brief on the syntax of filtering so I was wondering if this was an implemented feature in this serializer.

**Comment by gr0uch** [comment]
The JSON API spec is agnostic on what `filter` should do, and currently it's not fully implemented here yet. Fortune.js supports exact matches, ranges, and existence in its adapter, so a few filter queries can be done. If it's done here, it has to be documented here as specific to this serializer.

I was mostly concerned with implementing everything in the 1.0 spec, but not much more, don't have that much free time.

**Comment by yankeeinlondon** [comment]
Sure makes sense. I hope to get to a point where I can contribute to this effort soonish but right now it's just questions. Sorry and thanks for the prompt replies.

**Comment by yankeeinlondon** [comment]
For the queries which _are_ supported, is there somewhere I can refer to for syntax?

**Comment by gr0uch** [comment]
There's the implementation: https://github.com/fortunejs/fortune-json-api/blob/482fbd044c6181171cfc1984584b4fc5735a5c9a/lib/helpers.js#L268

And the tests: https://github.com/fortunejs/fortune-json-api/blob/482fbd044c6181171cfc1984584b4fc5735a5c9a/test/index.js#L207

Actually exact match is implemented, but not range and existence yet, so there is already a starting point.

**Comment by yankeeinlondon** [comment]
I'll close this for now unless you feel its better to keep open.

**Comment by gr0uch** [comment]
Keep it open, I would like to keep track of this.

**Comment by wolfgang42** [comment]
I have a need for an `IS [NOT] NULL` query, and I anticipate also needing ranges in the future. I'm thinking: 

<pre>
?filter[<var>field</var>][exists]=<var>true</var>&filter[<var>field</var>][min]=<var>5</var>&filter[<var>field</var>][max]=<var>10</var>
</pre>

(where `min` and `max` map to <code>{range: {<var>field</var>: [<var>min</var>, <var>max</var>]}}</code> with `null` if one is unspecified).

Does this look good to you? If it does I'll implement this and submit a PR.

**Comment by gr0uch** [comment]
@wolfgang42 that looks fine, since the spec is open to anything I'll entertain any PR.
