### ISSUE TITLE
Request body invalid

### ISSUE THREAD

**Issue by yankeeinlondon** [fortunejs/fortune-json-api#16]
I have no problems running GET requests but POST and PUTs seem to be causing errors that didn't exist in earlier builds. For instance, in the following  PUT request:

![2016-02-23_19-23-46](https://cloud.githubusercontent.com/assets/980757/13263907/a0dbd380-da63-11e5-8cd2-ac5007e74696.png)

In the terminal I can see that this results in:

> Unhandled rejection Error: Invalid method.
>     at Object.JsonSerializer.parsePayload (/project/api/node_modules/fortune/lib/net/http_json_serializer.js:204:11)
>     at /project/api/node_modules/fortune/lib/net/http_server.js:228:45

As for configuration at this point I'm simply providing model definitions ... in this case for the `actions` model.

**Comment by yankeeinlondon** [comment]
This issue should be in core, as the actual error seems to be in core (`/lib/dispatch/create.js:53`); i'll move it there when i get home.

**Comment by yankeeinlondon** [comment]
I think my original description is probably a bit misleading as I was mentioning the "PUT" verb (which JSON-API doesn't support) when what I meant was "PATCH". This error is thrown on any POST or PATCH call that I make whereas GET works fine. The failure point is in core here:

![image](https://cloud.githubusercontent.com/assets/980757/13270577/012666ce-da87-11e5-8176-21be1d9c3f3c.png)

![2016-02-23_23-44-36](https://cloud.githubusercontent.com/assets/980757/13270651/73c26ac0-da87-11e5-8c7f-07df0104f846.png)

And for reasons that are not yet clear to me `updates` is coming through as a key/value hash when it appears the code was expecting an array.

**Comment by gr0uch** [comment]
Ah, I'm pretty sure that `application/json` is incorrect. It should actually be `application/vnd.api+json`. According to the [spec](http://jsonapi.org/format/#content-negotiation-clients):

> Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters.

So actually it's correct that your payload is being rejected.

**Comment by yankeeinlondon** [comment]
Oh of course! Damn. Let me just check but that makes perfect sense. :+1:

**Comment by silentworks** [comment]
I don't think this is an issue as it seems the body data needs to be an array of object(s).

``` json
[
    {
        "importance": 8
    }
]
```

And all should work just as expected. //cc @ksnyde

**Comment by yankeeinlondon** [comment]
yes but it _shouldn't_ have to be an array of objects. :+1: The input it correct minus the wrong MIME type (which Postman doesn't support in it's dropdown).

**Comment by silentworks** [comment]
You sure because even the example on the fortune.js homepage says the payload is an array of object(s).

**Comment by gr0uch** [comment]
Just refer to the [tests](https://github.com/fortunejs/fortune-json-api/blob/master/test/index.js). This serializer fully conforms to the JSON API 1.0 spec, so you don't have to care about Fortune.js internals when using this.

**Comment by yankeeinlondon** [comment]
The tests seem to indicate payload is correct and switching to `application/vnd.api+json` parses the request correctly -- I believe -- but I'm getting:

> "The serializer for "application/vnd.api+json" does not exist."

![2016-02-24_00-08-14](https://cloud.githubusercontent.com/assets/980757/13271188/3817b332-da8b-11e5-99b8-7c152b33164b.png)

![2016-02-24_00-07-15](https://cloud.githubusercontent.com/assets/980757/13271202/4f398860-da8b-11e5-9b40-c8dab15b8faa.png)

And yet here is the configuration:

```
const models = Object.assign(referenceData, transactionalData, userData);
const options = {
  serializers: [
    [jsonApiSerializer, {}]
  ],
  adapter: [
    mongodbAdapter,
    {
      url: url,
    }
  ]
};
const store = fortune(models, options);
```

**Comment by gr0uch** [comment]
Oh this is another issue: Serializer has moved out of core. The reasoning is that serializers were HTTP-specific before anyways, so now it's HttpSerializer. It's now part of `net.http`. http://fortunejs.com/api/#fortune.net-http

I had to make some major breaking changes, hence version 3.

**Comment by yankeeinlondon** [comment]
ok, makes sense. I've corrected that in my configuration. Now I get the error:

> Cannot read property 'type' of undefined `fortune-json-api/lib/index.js:354:38`

![2016-02-24_00-36-16](https://cloud.githubusercontent.com/assets/980757/13271749/f5cd38b8-da8e-11e5-83ba-b13be53c96bb.png)

![image](https://cloud.githubusercontent.com/assets/980757/13271808/67a663b0-da8f-11e5-8b19-d01a1979e67e.png)

**Comment by yankeeinlondon** [comment]
super tired so need to rest on this for now. i'll look at it with fresh eyes tomorrow.

**Comment by yankeeinlondon** [comment]
Ok, i've sorted this out ... I guess it's down to the expected manner in which the serializer behaves. Let me explain ...

This request DOES work: `PATCH http://localhost:3000/actions/went-running` with the following body:

```
{
    "data": {
        "id": "went-running",
        "type": "actions",
            "attributes": {
                "importance": 8
            }
        }
    }
}
```

And this does fit a reading of the SPEC but I'm concerned about the redundancy here (example from JSON-API site):

![2016-02-24_15-27-05](https://cloud.githubusercontent.com/assets/980757/13290803/2f3e1cec-db0d-11e5-9990-897d30ed4838.png)

I have no issue with verbosity but redundancy within the spec seems problematic and since the "type" and "id" are typically expected to reside within the URL itself I think they should always be set automatically, even if the body has other values in them. Of course this is my _opinion_ and not something that I read in the spec.

I would be interested in any thoughts others might have.

**Comment by yankeeinlondon** [comment]
https://github.com/json-api/json-api/issues/966

It's being discussed on the JSON-API repo. Would it be reasonable to have an option on the serializer for something like this?

**Comment by gr0uch** [comment]
From my understanding of HTTP, URIs should be opaque. For example, I could have made the URI `/YXJ0aWNsZXMvMQ` map to the type `articles` with id `1`. In fact, this is how hypermedia should actually work: clients should not try to glean extra information from the URI. But in practice, clients tend to look too much into the URI when it's supposed to be something for the server to interpret.

Here's some background: https://www.w3.org/DesignIssues/Axioms.html#opaque

Also I think that issue is a completely separate concern, or correct me if I'm wrong (?)

**Comment by yankeeinlondon** [comment]
Ok in theory and sometimes in practice but in 90-95% of implementations the "common law" is that the two concerns are bound. One could argue that they shouldn't be but it would be hard to argue that they aren't. Furthermore, by allowing the routes values to be ignored/overwritten/separate this also means the routes value or meaning is diminished and it's ability reinforce scoping rules invalidated which would cause problems for a lot of the "route-based" middlewares wouldn't it? 

Imagine, for instance, I send a GET request to `/user/1` but instead in the JSON request I supply the type as `auth` and the id as **2**. Now the server can no longer use a route based rule to base its authorization logic on and instead must _ignore_ the route (which it was setup to distinguish) and instead authorize on the payload attributes.

To me this represents a good use-case for a configuration option but if you're opposed I can get around easily enough.

p.s. thanks for the link, found it a good read. as for whether the issue was the same/different ... obviously I thought it was the same but maybe I was wrong

**Comment by gr0uch** [comment]
What API clients shouldn't be doing is making assumptions about URIs. For example, it may be perfectly fine for the URI and the payload to not be in sync, it's the server's responsiblity to interpret it, but more importantly, the client should be actually using the hyperlinks provided by the server. If the server says that the URL for the user with id 2 is actually `/users/1`, then that's exactly where it's located. It's more of a matter of principle than any "practical" concerns over not duplicating data in the URI and payload.

**Comment by silentworks** [comment]
I agree with @0x8890 on this. I guess if the URL was `/socool/18839239820-182298M` It wouldn't really matter what the client url is as long as it serves up what I requested in the request body.

**Comment by yankeeinlondon** [comment]
So my concern wasn't with the client, it was the server but I'm going to close this regardless.
