### ISSUE TITLE
Client generated ID's

### ISSUE THREAD

**Issue by yankeeinlondon** [fortunejs/fortune-json-api#17]
I am having a problem adding a new record when the responsibility is on the client to generate the ID. I have the following body of a POST request:

```
{ 
    "data": {
        "type": "markers",
        "id": "pace_avg",
        "attributes": {
          "name": "Average Pace",
          "abbrev": "avg pace",
          "desc": "the average pace achieved during the session",
          "type": "exercise",
          "sub_type": "linear-sport"
        }
    }
} 
```

The error I get back is a `400` "the request body is invalid". The spec says that client generated ID's "may" be supported but if it does not then the error should be `403`. Having looked at the code I think the aim _is_ to support this -- although having an `id` in the URL causes a different error -- but I wanted to check that that is the case. 

In my case I'm importing data and this client generated scheme is unique (hence no UUID, etc.).

**Comment by yankeeinlondon** [comment]
Ok the problem seems to be related to inflection. It's almost surely user error but I'm unsure how to correct. In JSON-API's `index.js#parseCreate` it has identified the "type" as "marker" which is fine but in the `contextRequest` it is defined as "markers" (which is indeed what I've configured it as).

**Comment by gr0uch** [comment]
So is this a bug or not?

**Comment by yankeeinlondon** [comment]
No. I had some bad data that was the underlying cause.
