### ISSUE TITLE
No error handling for 404 errors

### ISSUE THREAD

**Issue by JoshTumath** [fortunejs/fortune-json-api#19]
If I try to access an API that doesn't exist, there are no error handling pages that are used. According to the JSON API spec, an array of errors should be returned in situations like this.

Fortune will need to handle these errors. If it's by design that it doesn't handle these errors, it would be helpful if the documentation could explain how to handle these errors in a way that conforms with the spec.

**Comment by gr0uch** [comment]
Are you sure? I'm pretty sure that this serializer is 100% compliant.

Look at [the tests](https://travis-ci.org/fortunejs/fortune-json-api). There are a few 404 responses tested, with the appropriate array of errors payload.

What are you getting?

**Comment by JoshTumath** [comment]
After looking into it further, it turns out that the error _is_ in fact being returned in the response body in the JSON API format. However, the reason why I didn't notice is because both Firefox and Edge currently don't render it. It works in Chrome.

So I'll report that browser bug to those browser vendors.
