### ISSUE TITLE
New version of Fortune breaks json-api tests

### ISSUE THREAD

**Issue by repl-andrew-ovens** [fortunejs/fortune-json-api#20]
The ^3.3.3 dependency in json-api is now getting the latest version of fortune. This version causes these tests to fail. Dropping the version to "3.3.3" works fine

**Comment by gr0uch** [comment]
I am aware of this, it's just the test fixtures, nothing much to worry about.

But thanks for opening this issue to keep track of it.

**Comment by gr0uch** [comment]
Updated tests https://github.com/fortunejs/fortune-json-api/commit/a05146f809384c58fbf29de55bf343726c6e92f7.
