### ISSUE TITLE
Pagination links not appearing

### ISSUE THREAD

**Issue by jsvg** [fortunejs/fortune-json-api#21]
Does pagination need to be explicitly configured beyond maxLimit? Pagination links are not appearing in my meta top-level cat. Also, ?page[limit]=x does not work. Looked through fortunejs.com docs. Couldn't find anything there either.

```
...
const listener = fortune.net.http(store, {
  serializers: [
    [ jsonApiSerializer,  {maxLimit: 5} ]
  ]
});
...
```

**Comment by gr0uch** [comment]
There were some regressions and they weren't tested before, I fixed it and added a test for pagination.

https://github.com/fortunejs/fortune-json-api/commit/a05146f809384c58fbf29de55bf343726c6e92f7

Note that the pagination links only appear if there is something to paginate, so querying for a limit of 1000 when there are less than 1000 resources will not show pagination links.

**Comment by jsvg** [comment]
Thanks for quick patch. The links appear now, however they aren't working as intended.

Clicking next (and first or last) appends the query params onto the end of the self url link, not adding 5 to the offset like it should.The prev link has next's behavior, but has a space in between appended items so it appears as a string.
E.g. 
self = /users?page[offset]=5&page[limit=5]
next = /users?page[offset]=5&page[limit=5]&page[offset]=5&page[limit]=5
first = /users?page[offset]=5&page[limit=5]&page[offset]=5&page[limit]=5
last = /users?page[offset]=5&page[limit=5]&page[offset]=5&page[limit]=5
prev = /users?page[offset]=5&page[limit=5] &page[offset]=5&page[limit]=5

**Comment by gr0uch** [comment]
Oops, re-opening this.

**Comment by gr0uch** [comment]
Should be resolved now https://github.com/fortunejs/fortune-json-api/commit/3b7ed31437502ca4a4f148a4b630bb3a374dae44.
