### ISSUE TITLE
Unhandled rejection TypeError: query[parameter].split is not a function

### ISSUE THREAD

**Issue by TheHandsomeCoder** [fortunejs/fortune-json-api#23]
I'm currently setting up my JSON-API and I'm getting this issue when testing the filter command with multiple entries

My URL is as follows
`localhost:9001/fencers?filter[firstName]=Scott,Ryan`

When I debug through with a single filter, the code in on [line 316 of the helper](https://github.com/fortunejs/fortune-json-api/blob/master/lib/helpers.js#L316) is trying to split the value of the query by a `,` however in the case of the URL above the value is already an array and thus can't be split.

What makes this even stranger, the tests for the fortune-json-api do something similar on [line 235](https://github.com/fortunejs/fortune-json-api/blob/master/test/index.js#L235) but this test passes correctly.

Is my URL malformed or is there an underlying issue? As a test I changed the line in the helper to the following and was able to get the expected response from the server.

`const value = (Array.isArray(query[parameter])) ? query[parameter] : query[parameter].split(',');`

**Comment by gr0uch** [comment]
The problem is most likely URI encoding. Here is the route from that test case:

```
/users?filter%5Bname%5D=John%20Doe%2CJane%20Doe&filter%5Bbirthday%5D=1992-12-07
```

Here the `qs` module does the URI encoding properly. Can you copy and paste the raw URI of your request?

Also the `uri-templates` library tries its best to cast values to arrays but it doesn't always work the same way based on the encoding.

**Comment by TheHandsomeCoder** [comment]
Yup that was it, looks like under the hood postman doesn't encode then URI by default. Cheers for the quick reply

**Comment by gr0uch** [comment]
P.S. thanks to your suggestion, I added support for unencoded commas: https://github.com/fortunejs/fortune-json-api/commit/34b5b9c3c7f94246fdf349eae7a9900d1b450e13
