### ISSUE TITLE
[Question] Filter parameter requires the internal field name

### ISSUE THREAD

**Issue by TheHandsomeCoder** [fortunejs/fortune-json-api#24]
When setting up the fortune server I defined a person resource as follows

`person: {
        firstName: { type: String },
        lastName: { type: String },
        gender: { type: String }      
 }
`
When this is returned from the server as per the JSON-API spec it is no longer camel case and is instead split by a hyphen.

However when I want to filter on a field I currently need to re-camel case the field name. Is this intended or a bug? I know the JSON-API is rather ambiguous on how filter should work, but it seems inconsistent to return a field that when sent back to the server in a different way throws an error.

**Comment by gr0uch** [comment]
Whoops, this is unintentional. The reason why is that in the recommendations section, they chose this naming scheme.

**Comment by TheHandsomeCoder** [comment]
Do you want a pull request for this or are you working on it yourself? I can probably find the time to have a go at it over the weekend

**Comment by gr0uch** [comment]
@TheHandsomeCoder Yes, please do.
