### ISSUE TITLE
Relationship links are not included when field is omitted

### ISSUE THREAD

**Issue by mfenniak** [fortunejs/fortune-json-api#29]
As discussed over at fortunejs/fortune#219, the links field on a relationship is omitted by the serializer when the relationship field itself is omitted (via options.fields[...relationship...] = false).

**Comment by gr0uch** [comment]
The problem seems to be related to this line: https://github.com/fortunejs/fortune-json-api/blob/806fad51fb7e62c78e07e7081cad81f6e061b1ab/lib/helpers.js#L198

It should actually iterate over all fields in the type definition.

**Comment by gr0uch** [comment]
Done https://github.com/fortunejs/fortune-json-api/commit/aefa206f6fc0d875451d71d2a6c27371e611034e.

**Comment by mfenniak** [comment]
Thanks!  You're an awesome open source maintainer.  👍
