### ISSUE TITLE
Duplicate URI decoding

### ISSUE THREAD

**Issue by pjlammertyn** [fortunejs/fortune-json-api#3]
also see [uri-templates issue #16: uri encoded %](https://github.com/geraintluff/uri-templates/issues/16)

in the [code](https://github.com/fortunejs/fortune-json-api/blob/a091835c11143ad244bb3f8b0c72c2ba5348e0e7/lib/helpers.js#L33-L35) you do double 'Decode URI Component only for the query string.'

this is incorrect because the uri-templates library already URI decodes the query string:

ex: in fortune-json-api you must supply incorrectly
`http://localhost:8001/api/messages?filter[body_like]=animi%2525`
because 
`http://localhost:8001/api/messages?filter[body_like]=animi%25`
wont work!

**Comment by gr0uch** [comment]
Oops! PR is welcome.

**Comment by gr0uch** [comment]
Nevermind, fixed in https://github.com/fortunejs/fortune-json-api/commit/afbfbc16927fd9a780c89da24eef91ab2540776f.
