### ISSUE TITLE
Getting error "The serializer for 'application/json' does not exist"

### ISSUE THREAD

**Issue by ezmiller** [fortunejs/fortune-json-api#35]
I'm trying to setup a fortune instance, but am getting an error when I do a simple GET:

```
{
  "jsonapi": {
    "version": "1.0"
  },
  "errors": [
    {
      "title": "UnsupportedError",
      "detail": "The serializer for \"application/json\" does not exist."
    }
  ]
}
```

My setup looks like this:

```
import http from 'http'
import fortune from 'fortune'
import jsonApiSerializer from 'fortune-json-api'

const store = fortune({
  movie: {
    title: String,
    rating: Number,
    director: 'director',
    cast: ['actor']
  },
  director: {
    name: String
  },
  actor: {
    name: String,
    movies: ['movie']
  }
})

const server = http.createServer(fortune.net.http(store, {
  serializers: [ jsonApiSerializer ]
}))

store.connect().then(() => server.listen(4000, () => {
  console.log('listening on 4000...')
}))
```

I'm a bit puzzled what is going on here given that it looks as though fortune automatically includes the JSON serializer plugin. Any help would be much appreciated. Thanks.

**Comment by gr0uch** [comment]
I will quote from the JSON API specification,

> Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters.
> 
> Clients that include the JSON API media type in their Accept header MUST specify the media type there at least once without any media type parameters.

http://jsonapi.org/format/#content-negotiation

So it looks like somewhere in your request, there is `application/json` _instead of_ `application/vnd.api+json`. Make sure that you `Accept` the correct media type, and also the correct `Content-Type` when sending data. The specification is quite rigid in this regard, and won't accept the generic media type.

Also, when you override `serializers`, you must include the defaults yourself, it won't get automatically added if it's overridden.

``` js
{
  // maybe you actually want to include the default json serializer as well...
  serializers: [ jsonApiSerializer, fortune.net.http.JsonSerializer ]
}
```

**Comment by ezmiller** [comment]
@0x8890 yep you were right! I didn't think it was relevant since it was just a GET request, but I was wrong. Looking closer at the settings in Postman, which is what I was using to make the request, I found that the headers included a content-type setting of "application/json". Thank you for the speedy response.
