### ISSUE TITLE
How do I get stuff into the adapter's meta parameter?

### ISSUE THREAD

**Issue by wolfgang42** [fortunejs/fortune-json-api#36]
My use case is an API which needs to check in the adaptor whether or not the user is authorized to view/edit specific fields. I'm using `express-ntlm` which adds a key `request.ntlm` with the authenticated information. However, I can't figure out how to get this information into the adaptor.

I tried reading through the `fortune-json-api` code but `meta` is overloaded to mean several different things and I can't find the one I need.

**Comment by gr0uch** [comment]
Yeah, it is a bit confusing because there are at least two meanings of `meta`:
- `meta` as defined by the JSON API spec
- `meta` as in the optional argument for adapters in fortune

How to pass information to the latter `meta` is by subclassing and extending this serializer:

``` js
const jsonApiSerializer = require('fortune-json-api')
const fortuneHTTP = require('fortune-http')

// Using dependency injection to get the class
const JsonApiSerializer = jsonApiSerializer(fortuneHTTP.Serializer)

class CustomSerializer extends JsonApiSerializer {
  processRequest(contextRequest, request, response) {
    contextRequest.meta.ntlm = request.ntlm
    return super(...arguments)
  }
}
```

Then the `meta` object that is passed to the adapter should contain the keys `headers`, `language`, and `ntlm`. I hope that answers your question.

**Comment by wolfgang42** [comment]
Aha, I somehow completely missed that you could use dependency injection to extend the serializer. I couldn't get the code you posted to work (it kept complaining about `Class constructor cannot be invoked without 'new'` and I couldn't figure out what it was doing) but with the nudge you gave me here's what I came up with:

``` js
const jsonApiSerializer = require('fortune-json-api')

const CustomSerializer = function(...args) {
    const Serializer = jsonApiSerializer(...args)

    const superProcessRequest = Serializer.prototype.processRequest
    Serializer.prototype.processRequest = function(contextRequest, request, response) {
        contextRequest.meta.ntlm = request.ntlm
        return superProcessRequest.call(this, contextRequest, request, response)
    }

    return Serializer
}
```
