### ISSUE TITLE
Bulk writes

### ISSUE THREAD

**Issue by jamesplease** [fortunejs/fortune-json-api#42]
JSON API doesn't support bulk writes out of the box, nor does it support extensions (yet), but it seems like Fortune has all of the pieces to enable this.

- The DB adapters support bulk write operations
- This is just a thin HTTP layer on top of those

I did a quick perusal of the documentation to try to figure out how to get this working for JSON API, but nothing immediately stood out to me. I don't need a fully working example, or anything, but I'm curious: would it be easy to extend this serializer to support bulk writes? If the answer is yes, could you point me to any relevant docs that could help me set that up?

Thanks!

p.s. Fortune, and this serializer, are both 👌

**Comment by gr0uch** [comment]
Yep, I know about this. The bulk extension used to be official and this serializer used to support it, but they backtracked and now it's not really supported anymore so I removed it here too.

You would just need to modify the `parsePayload` public method which calls the internal methods `parseCreate` and `parseUpdate` here. It would actually be really easy to do. Here's the relevant lines:

https://github.com/fortunejs/fortune-json-api/blob/daf3e4eb8a78df6254bf12ba5c964b1f26aa73dc/lib/index.js#L408-L412
https://github.com/fortunejs/fortune-json-api/blob/daf3e4eb8a78df6254bf12ba5c964b1f26aa73dc/lib/index.js#L511-L515

You would just have to remove the error and coerce singular objects into an array.

**Comment by jamesplease** [comment]
Thanks for the quick and helpful reply, @daliwali ! I'm going to try this out. I'll close this issue for now.
