### ISSUE TITLE
Adding tests using JSON Schema

### ISSUE THREAD

**Issue by jamesplease** [fortunejs/fortune-json-api#44]
JSON API exports a [schema](https://github.com/json-api/json-api/blob/509ee949c621cee5683c959d4268386e1a592b83/schema) that can be used to validate responses. It's intended to be a lenient definition, so it will not catch all invalid responses, but you can be confident that if it does error that there is a problem in your response.

This would have caught the issue with the root endpoint described in #43 , where ~~the links object is invalid~~ the response document is invalid.

If you'd like, I could add a validation check using the schema to the tests, using a lib like [is-my-json-valid](https://github.com/mafintosh/is-my-json-valid) or [ajv](https://github.com/epoberezkin/ajv). What do ya think? 🤔

**Comment by gr0uch** [comment]
PR would be very welcome for this!
