### ISSUE TITLE
Test that 204 responses actually return empty bodies

### ISSUE THREAD

**Issue by jamesplease** [fortunejs/fortune-json-api#47]
Right now the tests only check the status code, so requests that have a body will not break the tests. This isn't good imo. I can add this in if you're :+1: @daliwali

**Comment by gr0uch** [comment]
The only place where `204` is being set manually here is on one line, and that is when it's an `OPTIONS` request: https://github.com/fortunejs/fortune-json-api/blob/f46dc7e565d7c82c59b4f678f2dcce35dafd7c13/lib/helpers.js#L93

If a `204` is returned with a body that might be a bug in `fortune-http`. Actually I just looked and it seems correct actually: https://github.com/fortunejs/fortune-http/blob/0d6a79313dd46aeb481ed9a62594ff46f3f4f7cf/lib/index.js#L328-L334

Is there already a 204 response with a body? How can I reproduce this error?

**Comment by jamesplease** [comment]
Makes sense. I'm not sure if any of the 204s are returning bodies – I just noticed the tests don't always check the body. I was thinking we _should_ add tests for the bodies, even in 204 responses. Do you think that'd be more of an integration test, since it's just deferring to fortune-http for those responses?

**Comment by gr0uch** [comment]
I'm leaning towards just adding an assertion for an empty body in `fortune-http` here: https://github.com/fortunejs/fortune-http/blob/c7809a57abbedcce4d518f99ae84dbf54d27b79d/test/json.js#L173-L180
I'm not a big fan of over-testing stuff that is very unlikely to break.

**Comment by jamesplease** [comment]
Sounds good to me. I'll close this out, since it's an upstream thing.
