### ISSUE TITLE
Update error creation code

### ISSUE THREAD

**Issue by jamesplease** [fortunejs/fortune-json-api#48]
[This code](https://github.com/fortunejs/fortune-json-api/blob/5ef7ad19604755cba1a598b3d9dbada1394c2b8a/lib/index.js#L657-L662) generates invalid errors, such as:

```js
{
  title: 'MethodError',
  detail: 'Can not create with ID in the route.',
  isInputError: true
}
```

This particular error is generated in the test titled:

> "create record with wrong route should fail"

The spec describes the valid members of an error obj [here](http://jsonapi.org/format/#error-objects). The problem is that this code isn't very discerning about what ends up on the error obj, so keys like `isInputError` can end up there.

One solution would be to group all non-standard members under `meta`.

@daliwali , any thoughts on the best way to refactor this? I could write some code to make these tests pass, but I'm not sure if it'd maintain all of the behavior that you intended.

**Comment by gr0uch** [comment]
My response https://github.com/fortunejs/fortune-json-api/pull/45#issuecomment-294102431

**Comment by jamesplease** [comment]
Resolved by https://github.com/fortunejs/fortune-http/commit/bd2bd168a98e88722a4132cec75ba1838400e80e
