### ISSUE TITLE
Adapter is not connected when fetching related resources.

### ISSUE THREAD

**Issue by grahambates** [fortunejs/fortune-json-api#52]
In `initializeContext()` we call `adapter.find()` with the assumption that `adapter.connect()` has already been called. 

This is usually the case when fortune has already been initialised to fetch the primary resource e.g. when you GET `/myResource/123?include=myRelation`. This is not the case for the relationship endpoints `/myResource/123/myRelation` or `/myResource/123/relationships/myRelation`. Here the related resource is the *only* thing being fetched.

When using the postgres storage driver this results in an error where the connection pool object is undefined:
```
TypeError: Cannot read property 'query' of undefined
node_modules/fortune-postgres/lib/index.js:336:13
```

**Comment by grahambates** [comment]
Sorry, looks like this was down to an incorrect implementation on our part.

We weren't calling `fortune.connect()` when starting our web server and were relying on the fact that fortune auto-connects when the `find()` method is called. When initializing fortune correctly as per the docs e.g. `store.connect().then(() => server.listen(1337))` this is not an issue.

**Comment by gr0uch** [comment]
Glad that you figured it out yourself. I think it makes sense this way, either you start listening on HTTP first and connect to the database after the first request, or connect to the database first and then listen on HTTP.
