### ISSUE TITLE
inflectType not working on sparse fields

### ISSUE THREAD

**Issue by natevolker** [fortunejs/fortune-json-api#54]
Assuming you have a model of "article", with fields "title", "body", and "author", you would expect the following url:

```
/articles?fields[articles]=title,body
```

to suppress the "author" field from its output. This does not seem to be working.

However, if you make a request for:

```
/articles?fields[article]=title,body
```

the "author" field *is* suppressed.

**Comment by gr0uch** [comment]
Good point, this may be a bug here: https://github.com/fortunejs/fortune-json-api/blob/a9289e904c50bae0a6427f98b3c203e79fc46188/lib/helpers.js#L309

The type is not inflected. PR welcome, otherwise I can fix it.

**Comment by gr0uch** [comment]
This has been fixed to allow pluralized/dasherized type names: https://github.com/fortunejs/fortune-json-api/commit/e6822bdae94a1c50a6f1224254a59a566f450afc
