### ISSUE TITLE
Is there a way to disable Resource Linkage?

### ISSUE THREAD

**Issue by cecemel** [fortunejs/fortune-json-api#59]
It seems resource linkage is enabled by default, but this may explode the size of the json response if the has-many relationship is big.

Thanks!

**Comment by gr0uch** [comment]
@cecemel sort of. You can just omit it in the output, using an [output hook](http://fortune.js.org/api/#fortune-constructor):

```js
function output (context, record) {
  delete record.hasManyRelationshipField
}
```

That would be a server-side approach to prevent anyone from reading that data.

Or you could just [use fields](http://fortune.js.org/api/#adapter-find) on the client to selectively request what fields you want in the response.

**Comment by cecemel** [comment]
thx
