### ISSUE TITLE
Useless pagination links

### ISSUE THREAD

**Issue by blia** [fortunejs/fortune-json-api#6]
Hi, thanks for awesome lib.
But I think pagination links without initial query are meaningless.

For example, I'm requested some data
`/animals?page[limit]=1&page[offset]=1&sort=-name,birthday&include=owner.friends&filter[name]=Fido,Cuddles,Sniffles`
And response have a next links:

``` js
{ self: 'http://localhost:1337/animals',
  first: 'http://localhost:1337/animals?page[offset]=0&page[limit]=1',
  last: 'http://localhost:1337/animals?page[offset]=3&page[limit]=1',
  next: 'http://localhost:1337/animals?page[offset]=2&page[limit]=1',
  prev: 'http://localhost:1337/animals?page[offset]=0&page[limit]=1' },
```

To request the next page I have to manually create link.

**Comment by gr0uch** [comment]
Addressed in commit https://github.com/fortunejs/fortune-json-api/commit/a8d4dddc7f94d9a901da87d2b50deadeb73746d5.
