### ISSUE TITLE
IDs Casted to Numbers

### ISSUE THREAD

**Issue by jakesower** [fortunejs/fortune-json-api#61]
Related resources aren't being linked correctly when they have numeric IDs.

Example:

`POST /bears`
```json
{
  "type": "bears",
  "id": "4",
  "attributes": {
    "name": "Grumpy Bear",
  },
  "relationships": {
    "home": {
      "data": {
        "type": "homes",
        "id": "1"
      }
    }
  }
}
```

In this example, the server fails to complete with the following:

`BadRequestError: A related record for the field "home" was not found.`

The correct home record exists. The problem is that the home's ID of 1 is getting casted to a number, which fails to link correctly within fortune. When I remove the casting, the code works as expected.

I'm not sure why IDs are getting casted at all, given that they should always be treated as strings. It's not a difficult fix, and I'll be happy to put in a PR for it. However, understanding the reason for the casting would be helpful in case it breaks something else that I'm unaware of.

Thank you!

**Comment by gr0uch** [comment]
Oops, this can probably be turned off by default and be opt-in. The rationale is that strings or numbers can be used as IDs internally, but JSON API spec mandates that IDs must be strings. PR welcome!
