### ISSUE TITLE
URL Host on Links

### ISSUE THREAD

**Issue by nmsolis12** [fortunejs/fortune-json-api#69]
I'm trying to find a way to optionally automatically add the host to the links (self, related, etc...) in order provide a full url for my consumers as part of the response data.

Help is appreciated.

example: 
```json
 "data": [
    {
      "type": "categories",
      "id": "qORxXmZznVdmdyHcaBSH",
      "attributes": {
        "name": "My Name",
        "description": "My  Description"
      },
      "relationships": {
        "services": {
          "links": {
            "self": "http://localhost:8080/categories/qORxXmZznVdmdyHcaBSH/relationships/services",
            "related": "http://localhost:8080/categories/qORxXmZznVdmdyHcaBSH/services"
          },
          "data": [
            {
              "type": "services",
              "id": "5yEHz6mXHbIFSE/JMNbd"
            }
          ]
        }
      },
      "links": {
        "self": "http://localhost:8080/categories/qORxXmZznVdmdyHcaBSH"
      }
```

**Comment by gr0uch** [comment]
Hmm, it could be added as an option.

**Comment by amitassaraf** [comment]
This is easy if the library stops enforcing `/` at the start of the prefix option :)

**Comment by gr0uch** [comment]
Thanks for the suggestion @amitassaraf 

This has been committed as https://github.com/fortunejs/fortune-json-api/commit/f32541ddc11e96bb49204fcc45382c603ca500a2 and released.
