### ISSUE TITLE
ReferenceError: instance is not defined

### ISSUE THREAD

**Issue by eitan07** [fortunejs/fortune-json-api#75]
ReferenceError: instance is not defined
    at Object.<anonymous> (C:\Users\user\Desktop\fortune_cookie\fortune_cookie.js:7:30)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1118:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:982:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:875:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

**Comment by gr0uch** [comment]
`ReferenceError` is probably an issue in your code.
